#!/usr/bin/env bash
STRING="Hello World!"

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Configure redirection
sudo sed -i '/server_name _;/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart